app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="app"),
    path("<int:app_id>/", views.detail, name="detail"),
]

dash/urls.py
from django.urls import path
from . import views

app_name = "dash"
urlpatterns = [
    path("", views.index, name="index"),

    path("app/", views.app, name="app"),
    path("del/app/<int:app_id>", views.del_app, name="del_app"),
    path("pub/app/<int:app_id>", views.pub_app, name="pub_app"),
    path("new/app/", views.new_app, name="new_app"),
    path("detail/app/<int:app_id>", views.detail_app, name="detail_app"),
    path("copy/app/<int:app_id>", views.copy_app, name="copy_app"),

    path("menu/", views.menu, name="menu"),
    path("del/menu/<int:menu_id>", views.del_menu, name="del_menu"),
    path("new/menu/", views.new_menu, name="new_menu"),
    path("detail/menu/<int:menu_id>", views.detail_menu, name="detail_menu"),

    path("<int:menu_id>/menuitem/", views.menuItem, name="menuItem"),
    path("<int:menu_id>/del/menuitem/<int:menuItem_id>", views.del_menuItem, name="del_menuItem"),
    path("<int:menu_id>/new/menuitem/", views.new_menuItem, name="new_menuItem"),
    path("<int:menu_id>/detail/menuitem/<int:menuItem_id>", views.detail_menuItem, name="detail_menuItem"),

    path("page/", views.page, name="page"),
    path("del/page/<int:page_id>", views.del_page, name="del_page"),
    path("new/page/", views.new_page, name="new_page"),
    path("detail/page/<int:page_id>", views.detail_page, name="detail_page"),
]

zxc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='app', permanent=True),  name="home"),
    path('admin/', admin.site.urls),
    path('app/', include("app.urls")),
    path('dash/', include("dash.urls", namespace="dash")),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User


class Application(models.Model):
    name = models.CharField(max_length=20, unique=False)
    desc = models.CharField(max_length=100, blank=True)
    pub_date = models.DateTimeField(verbose_name="date published", null=True, blank=True, default=None)

    create_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    create_date = models.DateTimeField(verbose_name="date created", auto_now_add=True)

    def __str__(self):
        return self.name


class Menu(models.Model):
    name = models.CharField(max_length=10)
    app = models.ManyToManyField(Application)

    create_date = models.DateTimeField(verbose_name="date created", auto_now_add=True)

    def __str__(self):
        return self.name


class Page(models.Model):
    name = models.CharField(max_length=10, unique=True)
    content = models.TextField()

    create_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    create_date = models.DateTimeField(verbose_name="date created", auto_now_add=True)

    def __str__(self):
        return self.name


class MenuItem(models.Model):
    name = models.CharField(max_length=10)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    page = models.ForeignKey(Page, on_delete=models.PROTECT)

    create_date = models.DateTimeField(verbose_name="date created", auto_now_add=True)

    def __str__(self):
        return self.name

dash/models.py
from django.db import models

# Create your models here.

dash/forms.py
from django import forms
from app.models import Application, Menu, MenuItem, Page


class AppForm(forms.ModelForm):
    class Meta:
        model = Application

        fields = [
            "name",
            "desc",
        ]

        widgets = {
            "desc": forms.Textarea
        }


class MenuForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["app"].queryset = Application.objects.filter(create_user__isnull=False)
        self.fields['app'].label_from_instance = lambda obj: "%s(%s)" % (obj.name, obj.pk)

    class Meta:
        model = Menu

        fields = [
            "name",
            "app",
        ]


class MenuItemForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["page"].queryset = Page.objects.filter(create_user__isnull=False)

    class Meta:
        model = MenuItem
        fields = [
            "name",
            "page",
        ]


class PageForm(forms.ModelForm):
    class Meta:
        model = Page

        fields = [
            "name",
            "content",
        ]

dash/views.py
from django.utils import timezone

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.decorators.clickjacking import xframe_options_exempt

from app.models import Application, Menu, MenuItem, Page
from .forms import AppForm, MenuForm, PageForm, MenuItemForm


@login_required
def index(request):
    app_count = Application.objects.all().count()
    menu_count = Menu.objects.all().count()
    page_count = Page.objects.all().count()
    return render(request, "dash/index.html", {
        "app_count": app_count,
        "menu_count": menu_count,
        "page_count": page_count,
    })


@login_required
def app(request):
    apps = Application.objects.filter(create_user__isnull=False).order_by('-create_date')
    return render(request, "dash/app/app.html", {
        "apps": apps
    })


@login_required
def new_app(request):
    if request.method == 'POST':
        form = AppForm(request.POST)
        if form.is_valid():
            app = form.save(commit=False)
            app.create_user = request.user
            app.save()
            messages.success(request, "Create {} Success".format(app.name))
            return HttpResponseRedirect(reverse('dash:app'))
    else:
        form = AppForm()
    return render(request, "dash/app/create.html", {"form": form})


@login_required
def detail_app(request, app_id):
    app = get_object_or_404(Application, pk=app_id)
    if request.method == 'POST':
        form = AppForm(request.POST, instance=app)
        if form.is_valid():
            form.save()
            messages.success(request, "Update {} Success".format(app.name))
            return HttpResponseRedirect(reverse('dash:app'))
    else:
        form = AppForm(instance=app)
    return render(request, "dash/app/detail.html", {"form": form})


@login_required
def del_app(request, app_id):
    app = get_object_or_404(Application, pk=app_id)
    app.delete()
    messages.success(request, "Delete {} Success".format(app.name))
    return HttpResponseRedirect(reverse('dash:app'))


@login_required
def copy_app(request, app_id):
    old = get_object_or_404(Application, pk=app_id)
    old_menus = old.menu_set.all()
    old.create_date = None
    old.pk = None
    old.save()
    for m in old_menus:
        old.menu_set.add(m)
    return HttpResponseRedirect(reverse("dash:app"))


@login_required
def pub_app(request, app_id):
    app = get_object_or_404(Application, pk=app_id)
    action = "Publish"
    if app.pub_date is None:
        app.pub_date = timezone.now()
    else:
        app.pub_date = None
        action = "UnPublish"
    app.save()
    messages.success(request, "{} {} Success".format(action, app.name))
    return HttpResponseRedirect(reverse('dash:app'))


@login_required
def menu(request):
    if request.method == 'GET':
        menus = Menu.objects.order_by('-create_date')
        return render(request, "dash/menu/menu.html", {
            "menus": menus
        })

    return render(request, "dash/index.html")


@login_required
def new_menu(request):
    if request.method == 'POST':
        form = MenuForm(request.POST)
        if form.is_valid():
            menu = form.save(commit=False)
            menu.save()
            messages.success(request, "Create {} Success".format(menu.name))
            return HttpResponseRedirect(reverse('dash:menu'))
    else:
        form = MenuForm()
    return render(request, "dash/menu/create.html", {"form": form})


@login_required
def detail_menu(request, menu_id):
    menu = get_object_or_404(Menu, pk=menu_id)
    if request.method == 'POST':
        form = MenuForm(request.POST, instance=menu)
        if form.is_valid():
            form.save()
            messages.success(request, "Create {} Success".format(menu.name))
            return HttpResponseRedirect(reverse('dash:menu'))
    else:
        form = MenuForm(instance=menu)
    return render(request, "dash/menu/detail.html", {"form": form, "menuId": menu_id})


@login_required
def del_menu(request, menu_id):
    menu = get_object_or_404(Menu, pk=menu_id)
    menu.delete()
    messages.success(request, "Delete {} Success".format(menu.name))
    return HttpResponseRedirect(reverse('dash:menu'))


@xframe_options_exempt
@login_required
def menuItem(request, menu_id):
    if request.method == 'GET':
        menuItems = MenuItem.objects.filter(menu_id=menu_id).order_by('-create_date')
        return render(request, "dash/menu/menuItem/menuItem.html", {
            "menuItems": menuItems,
            "menuId": menu_id
        })

    return render(request, "dash/index.html")


@xframe_options_exempt
@login_required
def new_menuItem(request, menu_id):
    menu = get_object_or_404(Menu, pk=menu_id)
    if request.method == 'POST':
        form = MenuItemForm(request.POST)
        if form.is_valid():
            menuItem = form.save(commit=False)
            menuItem.menu = menu
            menuItem.save()
            messages.success(request, "Create {} Success".format(menu.name))
            return HttpResponseRedirect(reverse('dash:menuItem', kwargs={"menu_id": menu_id}))
    else:
        form = MenuItemForm()
    return render(request, "dash/menu/menuItem/create.html", {"form": form, "menuId": menu_id})


@xframe_options_exempt
@login_required
def detail_menuItem(request, menu_id, menuItem_id):
    menuItem = get_object_or_404(MenuItem, pk=menuItem_id)
    if request.method == 'POST':
        form = MenuItemForm(request.POST, instance=menuItem)
        if form.is_valid():
            form.save()
            messages.success(request, "Update {} Success".format(menu.name))
            return HttpResponseRedirect(reverse('dash:menuItem', kwargs={"menu_id": menu_id}))
    else:
        form = MenuItemForm(instance=menuItem)
    return render(request, "dash/menu/menuItem/detail.html", {"form": form, "menuId": menu_id})


@xframe_options_exempt
@login_required
def del_menuItem(request, menu_id, menuItem_id):
    menuItem = get_object_or_404(MenuItem, pk=menuItem_id, menu_id=menu_id)
    menuItem.delete()
    messages.success(request, "Delete {} Success".format(menuItem.name))
    return HttpResponseRedirect(reverse('dash:menuItem', kwargs={"menu_id": menu_id}))


@login_required
def page(request):
    if request.method == 'GET':
        pages = Page.objects.order_by('-create_date')
        return render(request, "dash/page/page.html", {
            "pages": pages
        })

    return render(request, "dash/index.html")


@login_required
def new_page(request):
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit=False)
            page.create_user = request.user
            page.save()
            messages.success(request, "Create {} Success".format(page.name))
            return HttpResponseRedirect(reverse('dash:page'))
    else:
        form = PageForm()
    return render(request, "dash/page/create.html", {"form": form})


@login_required
def detail_page(request, page_id):
    page = get_object_or_404(Page, pk=page_id)
    if request.method == 'POST':
        form = PageForm(request.POST, instance=page)
        if form.is_valid():
            form.save()
            messages.success(request, "Update {} Success".format(page.name))
            return HttpResponseRedirect(reverse('dash:page'))
    else:
        form = PageForm(instance=page)
    return render(request, "dash/page/detail.html", {"form": form})


@login_required
def del_page(request, page_id):
    page = get_object_or_404(Page, pk=page_id)
    page.delete()
    messages.success(request, "Delete {} Success".format(page.name))
    return HttpResponseRedirect(reverse('dash:page'))

dash/templates/dash/app.html
{% extends "dash/base.html" %}

{% block title %}Dashboard - Application{% endblock %}

{% block content %}
    <t-table ref="table" row-key="index" table-layout="auto" :columns="columns" :max-height="maxHeight" :data="apps"
             :pagination="pagination" :filter-value.sync="filterValue" @filter-change="onFilterChange"
             :header-affixed-top="headerAffixedTop" lazy-load>
        <template #operation="{ row }">
            <t-space>
                <t-link :theme="row.pub_date?'warning':'success'" :href="row.pub_url">
                    [[ row.pub_date ? '下线' : '发布' ]]
                </t-link>

                <t-link theme="danger" :href="row.del_url">
                    删除
                </t-link>
            </t-space>
        </template>
    </t-table>
{% endblock %}

{% block script %}
    <script>
        const messages = [
            {% for message in messages %}
                {
                    level: "{{ message.level }}",
                    msg: "{{ message }}",
                    tags: "{{ message.tags }}",
                },
            {% endfor %}
        ]
        const columns = [
            {colKey: 'id', title: 'ID'},
            {
                colKey: 'name', title: 'Name', filter: {
                    type: 'input',
                    resetValue: '',
                    // 按下 Enter 键时也触发确认搜索
                    confirmEvents: ['onEnter'],
                    props: {
                        placeholder: '输入关键词过滤',
                    },
                },
            },
            {colKey: 'desc', title: 'Description'},
            {colKey: 'pub_date', title: 'Publish At'},
            {colKey: 'create_user', title: 'Create By'},
            {colKey: 'create_date', title: 'Create At'},
            {colKey: 'operation', title: 'Operation', fixed: 'right'},
        ]

        const apps = [
            {% for app in apps %}
                {
                    "id": "{{ app.pk }}",
                    "name": "{{ app.name }}",
                    "desc": "{{ app.desc }}",
                    "pub_date": "{{ app.pub_date | date:'c' }}",
                    "create_user": "{{ app.create_user.username }}",
                    "create_date": "{{ app.create_date | date:'c' }}",
                    "del_url": "{% url "dash:del_app" app.pk %}",
                    "pub_url": "{% url "dash:pub_app" app.pk %}",
                },
            {% endfor %}

        ]
        const app = Vue.createApp({
            delimiters: ["[[", "]]"],
            data() {
                return {
                    activeMenu: 'app',
                    maxHeight: 500,
                    collapsed: localStorage.getItem("collapsed") === 'true',
                    columns: columns,
                    apps: apps,
                    filterValue: {},
                    headerAffixedTop: {
                        offsetTop: 80,
                    }
                }
            },
            computed: {
                pagination() {
                    return {
                        total: this.apps.length,
                        defaultCurrent: 1,
                        defaultPageSize: 14,
                        showJumper: true,
                        showPageSize: false,
                    }
                }
            },
            mounted() {
                this.setTableHeight()
                window.addEventListener("resize", this.setTableHeight);
                if (messages.length) {
                    messages.forEach(m => {
                        this.$message(m.tags, m.msg)
                    })
                }
            },
            unmounted() {
                window.removeEventListener("resize", this.setTableHeight);
            },
            methods: {
                setTableHeight() {
                    const rect = document.querySelector('main.t-layout__content>div')?.getBoundingClientRect()
                    this.maxHeight = rect['height']
                },
                changeCollapsed: function () {
                    this.collapsed = !this.collapsed
                    localStorage.setItem("collapsed", this.collapsed)
                    this.setTableHeight()

                    // TODO: not work
                    // header-affixed-top effect table width
                    this.$refs.table.refreshTable()
                },
                onFilterChange(filters, ctx) {
                    this.filterValue = filters;
                    this.apps = _.filter(apps, item => _.includes(item.name, _.get(filters, 'name', '')))
                },

            }
        })

        app.use(TDesign)
        app.mount('#app');
    </script>
{% endblock %}

dash/templates/dash/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %} Dashboard {% endblock %}</title>
    {% include "common/vue.html" %}
    {% include "common/lib.html" %}

    <style>
        html,body {
            margin: 0;
        }
        :root {
            --component-border: #e7e7e7;
        }

        main.t-layout__content {
            padding: 24px 24px 0;
        }

        main.t-layout__content > div {
            background: #fff;
            box-sizing: border-box;
            padding: 8px;
            height: calc(100vh - 150px);
            overflow: scroll;
            -ms-overflow-style: none;  /* Internet Explorer 10+ */
            scrollbar-width: none;  /* Firefox */
        }
        main.t-layout__content > div::-webkit-scrollbar{
            display: none;
        }
    </style>

    {% block style %}
    {% endblock %}

</head>
<body>

<div id="app">
    <t-layout>
        <t-header>
            <t-head-menu value="item1" height="120px">
                <template #logo>
                    <h1>ZXC</h1>
                </template>

                <template #operations>
                    {% if user.is_staff %}
                        <a href="{% url "admin:index" %}">
                            <t-icon class="t-menu__operations-icon" name="system-setting"/>
                        </a>
                    {% endif %}
                    <a href="{% url "app" %}">
                        <t-icon class="t-menu__operations-icon" name="home"/>
                    </a>

                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <t-button type="submit" shape="square" variant="text">
                            <template #icon>
                                <t-icon name="logout"/>
                            </template>
                        </t-button>
                    </form>
                </template>
            </t-head-menu>
        </t-header>
        <t-layout>
            <t-aside style="border-top: 1px solid var(--component-border)" :width="collapsed?'auto':''">
                <t-menu theme="light" :value="activeMenu" :collapsed="collapsed">
                    <t-menu-item value="dashboard" href="{% url "dash:index" %}">
                        <template #icon>
                            <t-icon name="dashboard"/>
                        </template>
                        看板
                    </t-menu-item>
                    <t-menu-item value="app" href="{% url "dash:app" %}">
                        <template #icon>
                            <t-icon name="application"/>
                        </template>
                        应用
                    </t-menu-item>

                    <t-menu-item value="menu" href="{% url "dash:menu" %}">
                        <template #icon>
                            <t-icon name="menu"/>
                        </template>
                        菜单
                    </t-menu-item>

                    <t-menu-item value="page" href="{% url "dash:page" %}">
                        <template #icon>
                            <t-icon name="html5"/>
                        </template>
                        页面
                    </t-menu-item>

                    <template #operations>
                        <t-button class="t-demo-collapse-btn" variant="text" shape="square" @click="changeCollapsed">
                            <template #icon>
                                <t-icon :name="collapsed?'menu-fold':'menu-unfold'"/>
                            </template>
                        </t-button>
                    </template>
                </t-menu>
            </t-aside>
            <t-layout>
                <t-content>
                    <div>
                        {% block content %}

                        {% endblock %}
                    </div>
                </t-content>
                <t-footer>Copyright @ 2019-[[ new Date().getFullYear() ]] ZXC. All Rights Reserved</t-footer>
            </t-layout>
        </t-layout>
    </t-layout>

</div>

{% block script %}
{% endblock %}
</body>
</html>

dash/templates/dash/menu.html
{% extends "dash/base.html" %}

{% block title %}Dashboard - Menu{% endblock %}

{% block content %}
    <t-table ref="table" row-key="index" table-layout="auto" :columns="columns" :max-height="maxHeight" :data="apps"
             :pagination="pagination" :filter-value.sync="filterValue" @filter-change="onFilterChange"
             :header-affixed-top="headerAffixedTop" lazy-load>
        <template #operation="{ row }">
            <t-space>

                <t-link theme="danger" :href="row.del_url">
                    删除
                </t-link>
            </t-space>
        </template>
    </t-table>
{% endblock %}

{% block script %}
    <script>
        const messages = [
            {% for message in messages %}
                {
                    level: "{{ message.level }}",
                    msg: "{{ message }}",
                    tags: "{{ message.tags }}",
                },
            {% endfor %}
        ]
        const columns = [
            {colKey: 'id', title: 'ID'},
            {
                colKey: 'name', title: 'Name', filter: {
                    type: 'input',
                    resetValue: '',
                    // 按下 Enter 键时也触发确认搜索
                    confirmEvents: ['onEnter'],
                    props: {
                        placeholder: '输入关键词过滤',
                    },
                },
            },
            {colKey: 'app', title: 'Application'},
            {colKey: 'create_date', title: 'Create At'},
            {colKey: 'operation', title: 'Operation', fixed: 'right'},
        ]

        const apps = [
            {% for app in menus %}
                {
                    "id": "{{ app.pk }}",
                    "name": "{{ app.name }}",
                    "app": "{{ app.app.name }}",
                    "create_date": "{{ app.create_date | date:'c' }}",
                    "del_url": "{% url "dash:del_menu" app.pk %}",
                },
            {% endfor %}

        ]
        const app = Vue.createApp({
            delimiters: ["[[", "]]"],
            data() {
                return {
                    activeMenu: 'menu',
                    maxHeight: 500,
                    collapsed: localStorage.getItem("collapsed") === 'true',
                    columns: columns,
                    apps: apps,
                    filterValue: {},
                    headerAffixedTop: {
                        offsetTop: 80,
                    }
                }
            },
            computed: {
                pagination() {
                    return {
                        total: this.apps.length,
                        defaultCurrent: 1,
                        defaultPageSize: 14,
                        showJumper: true,
                        showPageSize: false,
                    }
                }
            },
            mounted() {
                this.setTableHeight()
                window.addEventListener("resize", this.setTableHeight);
                if (messages.length) {
                    messages.forEach(m => {
                        this.$message(m.tags, m.msg)
                    })
                }
            },
            unmounted() {
                window.removeEventListener("resize", this.setTableHeight);
            },
            methods: {
                setTableHeight() {
                    const rect = document.querySelector('main.t-layout__content>div')?.getBoundingClientRect()
                    this.maxHeight = rect['height']
                },
                changeCollapsed: function () {
                    this.collapsed = !this.collapsed
                    localStorage.setItem("collapsed", this.collapsed)
                    this.setTableHeight()

                    // TODO: not work
                    // header-affixed-top effect table width
                    this.$refs.table.refreshTable()
                },
                onFilterChange(filters, ctx) {
                    this.filterValue = filters;
                    this.apps = _.filter(apps, item => _.includes(item.name, _.get(filters, 'name', '')))
                },

            }
        })

        app.use(TDesign)
        app.mount('#app');
    </script>
{% endblock %}

dash/templates/dash/page.html
{% extends "dash/base.html" %}

{% block title %}Dashboard - Page{% endblock %}

{% block content %}
    <t-table ref="table" row-key="index" table-layout="auto" :columns="columns" :max-height="maxHeight" :data="apps"
             :pagination="pagination" :filter-value.sync="filterValue" @filter-change="onFilterChange"
             :header-affixed-top="headerAffixedTop" lazy-load>
        <template #operation="{ row }">
            <t-space>

                <t-link theme="danger" :href="row.del_url">
                    删除
                </t-link>
            </t-space>
        </template>
    </t-table>
{% endblock %}

{% block script %}
    <script>
        const messages = [
            {% for message in messages %}
                {
                    level: "{{ message.level }}",
                    msg: "{{ message }}",
                    tags: "{{ message.tags }}",
                },
            {% endfor %}
        ]
        const columns = [
            {colKey: 'id', title: 'ID'},
            {
                colKey: 'name', title: 'Name', filter: {
                    type: 'input',
                    resetValue: '',
                    // 按下 Enter 键时也触发确认搜索
                    confirmEvents: ['onEnter'],
                    props: {
                        placeholder: '输入关键词过滤',
                    },
                },
            },
            {colKey: 'create_date', title: 'Create At'},
            {colKey: 'operation', title: 'Operation', fixed: 'right'},
        ]

        const apps = [
            {% for app in pages %}
                {
                    "id": "{{ app.pk }}",
                    "name": "{{ app.name }}",
                    "menuitem": [
                        {% for item in app.menuitem_set.all %}
                            {
                              id: "{{ item.pk }}",
                              name: "{{ item.name }}",
                            },
                        {% endfor %}

                    ],
                    "create_date": "{{ app.create_date | date:'c' }}",
                    "del_url": "{% url "dash:del_page" app.pk %}",
                },
            {% endfor %}

        ]
        const app = Vue.createApp({
            delimiters: ["[[", "]]"],
            data() {
                return {
                    activeMenu: 'page',
                    maxHeight: 500,
                    collapsed: localStorage.getItem("collapsed") === 'true',
                    columns: columns,
                    apps: apps,
                    filterValue: {},
                    headerAffixedTop: {
                        offsetTop: 80,
                    }
                }
            },
            computed: {
                pagination() {
                    return {
                        total: this.apps.length,
                        defaultCurrent: 1,
                        defaultPageSize: 14,
                        showJumper: true,
                        showPageSize: false,
                    }
                }
            },
            mounted() {
                this.setTableHeight()
                window.addEventListener("resize", this.setTableHeight);
                if (messages.length) {
                    messages.forEach(m => {
                        this.$message(m.tags, m.msg)
                    })
                }
            },
            unmounted() {
                window.removeEventListener("resize", this.setTableHeight);
            },
            methods: {
                setTableHeight() {
                    const rect = document.querySelector('main.t-layout__content>div')?.getBoundingClientRect()
                    this.maxHeight = rect['height']
                },
                changeCollapsed: function () {
                    this.collapsed = !this.collapsed
                    localStorage.setItem("collapsed", this.collapsed)
                    this.setTableHeight()

                    // TODO: not work
                    // header-affixed-top effect table width
                    this.$refs.table.refreshTable()
                },
                onFilterChange(filters, ctx) {
                    this.filterValue = filters;
                    this.apps = _.filter(apps, item => _.includes(item.name, _.get(filters, 'name', '')))
                },

            }
        })

        app.use(TDesign)
        app.mount('#app');
    </script>
{% endblock %}